routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/admin', 'AdminController@index')->name('admin');
Route::get('/admin/dashboard', 'DashboardController@index')->name('admin/dashboard');
Route::resource('admin/client','ClientController');
Route::resource('admin/transaction','TransactionController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use App\Client;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = 10;
        $transactions = Transaction::orderBy('id', 'desc')->paginate($pages);
        return view('transaction.index', compact('transactions'))
            ->with('i', (request()->input('page',1) -1)* $pages );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('transaction.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'client_id' => 'present|required',
            'amount' => 'present|required|numeric',
            'created_at' => 'present|required',
        ]);
        $transaction = Transaction::create($request->all());

        return redirect()->route('transaction.index')->with('success', 'New transaction created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        return view('transaction.show',compact('transaction'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {

        return view('transaction.edit', compact('transaction'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        $request->validate([
            'client_id' => 'present|required',
            'amount' => 'present|required|numeric',
            'created_at' => 'present|required',
        ]);

        $transaction->update($request->all());

        return redirect()->route('transaction.index')->with('success', 'Transaction updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction $transaction
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Transaction $transaction)
    {
        $transaction->delete();
        return redirect()->route('transaction.index')->with('success', 'Transaction deleted successfully');
    }
}

resources/views/transaction/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <h3>New transaction</h3>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('transaction.store')}}" method="post">
            @csrf

            @if ($clients = App\Client::all())
                <label for="client_id">Client ID :</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="client_id">Client</label>
                    </div>
                    <select name="client_id" class="custom-select @error('client_id') is-invalid @enderror">
                        <option value=" " selected></option>

                        @foreach ($clients as $client)
                            <option value="{{ $client->id }}">{{ $client->id }} - {{ $client->first_name }} {{ $client->last_name }}</option>
                        @endforeach
                    </select>
                </div>
            @endif

            <div class="form-group">
                <label for="amount">Amount :</label>
                <input type="number" min="0.00" max="999999.99" step="0.01" class="form-control @error('amount') is-invalid @enderror" name="amount" placeholder="xxxx.xx" value="{{ old('amount') }}" pattern="\d+(\.\d{2})?" autocomplete="amount" autofocus>
            </div>
            <div class="form-group">
                <label for="created_at">Transaction Date :</label>
                <input type="text" id="created_at" class="form-control @error('created_at') is-invalid @enderror" name="created_at" value="{{ old('created_at') }}" required autocomplete="created_at" autofocus>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                <a href="{{route('transaction.index')}}" class="btn btn-sm btn-danger">Cancel</a>
            </div>

        </form>

    </div>
@endsection

resources/views/transaction/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">

        <h3>Edit transaction</h3>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('transaction.update',$transaction->id)}}" method="post">
            @csrf
            @method('PUT')

            @if ($clients = App\Client::all())
                <label for="client_id">Client ID :</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="client_id">Client</label>
                    </div>
                    <select name="client_id" class="custom-select @error('client_id') is-invalid @enderror">
                        <option value="{{$transaction->client_id}}" selected>Current</option>

                        @foreach ($clients as $client)
                            <option value="{{ $client->id }}">{{ $client->id }} - {{ $client->first_name }} {{ $client->last_name }}</option>
                        @endforeach
                    </select>
                </div>
            @endif

            <div class="form-group">
                <label for="amount">Amount :</label>
                <input type="number" min="0.00" max="999999.99" step="0.01" value="{{$transaction->amount}}" class="form-control @error('amount') is-invalid @enderror" name="amount" placeholder="xxxx.xx" pattern="\d+(\.\d{2})?" autocomplete="amount" autofocus>
            </div>
            <div class="form-group">
                <label for="created_at">Transaction Date :</label>
                <input type="text" value="{{$transaction->created_at}}" id="created_at" class="form-control @error('created_at') is-invalid @enderror" name="created_at" required autocomplete="created_at" autofocus>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-sm btn-success">Save</button>
                <a href="{{route('transaction.index')}}" class="btn btn-sm btn-danger">Cancel</a>
            </div>
        </form>
    </div>
@endsection

resources/views/transaction/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="d-flex justify-content-between flex-wrap">
            <div class="p-2">
                <h3>Transactions</h3>
            </div>
            <div class="p-2">
                <a class="btn btn-sm btn-success mb-4" href="{{ route('transaction.create') }}"><i class="far fa-plus-square"> New</i></a>
            </div>
        </div>

        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{$message}}</p>
            </div>
        @endif
        <div class="table-responsive">
            <table class="table table-hover table-sm">
                <thead>
                    <tr>
                        <th width="5%" scope="col">#</th>
                        <th class="d-none d-sm-block" width="20%" scope="col">Client</th>
                        <th width="20%" scope="col">Amount</th>
                        <th width="20%" scope="col">Date</th>
                        <th width="35%" scope="col" class="text-right">Action</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($transactions as $transaction)
                        <tr>
                            <th scope="row">{{$transaction->id}}</th>
                            <td class="d-none d-sm-block">
                                @if(isset($transaction->client_id))
                                    <a class="text-dark" href="{{route('client.show',$transaction->client_id)}}" target="_blank"    >
                                        @if ($client = App\Client::find($transaction->client_id)) @endif
                                        {{ $client->first_name }} {{ $client->last_name }}
                                    </a>
                                @endif
                            </td>
                            <td>{{$transaction->amount}}</td>
                            <td>{{$transaction->created_at->format('d M Y')}}</td>
                            <td class="text-right">
                                <form action="{{ route('transaction.destroy', $transaction->id) }}" method="post">
                                    <a class="btn btn-sm btn-primary" href="{{route('transaction.show',$transaction->id)}}"><i class="far fa-eye"></i></a>
                                    <a class="btn btn-sm btn-warning" href="{{route('transaction.edit',$transaction->id)}}"><i class="far fa-edit"></i></a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-danger"><i class="far fa-trash-alt"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        <div>

        {!! $transactions->links() !!}
    </div>
@endsection

resources/views/transaction/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-5 mx-auto">
                <h3>Transaction Details</h3>
                <hr>
                <div class="card">
                    <div class="card-header text-right">
                        <a href="{{route('transaction.index')}}" class="btn btn-sm btn-danger"><i class="fas fa-times"></i></a>
                    </div>
                    <div class="card-body">
                        @if(isset($transaction->client_id))
                            <h5 class="card-title"><strong>Client</strong></h5>
                            @if ($client = App\Client::find($transaction->client_id))
                                <h6 class="card-title"><strong>ID: </strong>{{ $client->id }}</h6>
                                <h6 class="card-title"><strong>Email: </strong>{{ $client->email }}</h6>
                                <h6 class="card-title mb-4"><strong>Name: </strong>
                                    <a class="text-dark" href="{{route('client.show',$transaction->client_id)}}"
                                       target="_blank">{{ $client->first_name }} {{ $client->last_name }}
                                    </a>
                                </h6>
                            @endif
                        @endif
                        <h5 class="card-title"><strong>Transaction</strong></h5>
                        <h6 class="card-title"><strong>Date: </strong>{{$transaction->created_at->format('d M Y')}}</h6>
                        <h6 class="card-title"><strong>Amount: </strong>{{$transaction->amount}}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection