routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/admin', 'AdminController@index')->name('admin');
Route::get('/admin/dashboard', 'DashboardController@index')->name('admin/dashboard');
Route::resource('admin/client','ClientController');
Route::resource('admin/transaction','TransactionController');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'avatar', 'email',
    ];

}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = 10;
        $clients = Client::orderBy('id', 'desc')->paginate($pages);
        return view('client.index', compact('clients'))
            ->with('i', (request()->input('page',1) -1)* $pages );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required',
            'avatar' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
        $client = Client::create($request->all());

        if($request->hasFile('avatar'))
        {

            $avatar_filename = 'avatar_user_'.$client->id.'.'.request()->avatar->getClientOriginalExtension();

            $request->file('avatar')->storeAs(
                'avatars', $avatar_filename
            );

            // Updates avatar filename
            $client->avatar = $avatar_filename;
            $client->save();
        }

        return redirect()->route('client.index')->with('success', 'New client created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        return view('client.show',compact('client'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {

        return view('client.edit', compact('client'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $request->validate([
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required',
            'avatar' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $client->update($request->all());

        if($request->hasFile('avatar'))
        {

            $avatar_filename = 'avatar_user_'.$client->id.'.'.request()->avatar->getClientOriginalExtension();

            $request->file('avatar')->storeAs(
                'avatars', $avatar_filename
            );

            // Updates avatar filename
            $clientdata = Client::find($client->id);
            $clientdata->avatar = $avatar_filename;
            $clientdata->save();
        }


        return redirect()->route('client.index')->with('success', 'Client updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client $client
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Client $client)
    {
        $client->delete();
        return redirect()->route('client.index')->with('success', 'Client deleted successfully');
    }
}

resources/views/client/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">

        <h3>New client</h3>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('client.store')}}" method="post" enctype="multipart/form-data">
            @csrf

            <div class="form-group">
                <label for="email">Email :</label>
               <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>
            </div>
            <div class="form-group">
                <label for="first_name">First Name :</label>
                <input type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name') }}" required autocomplete="first_name" autofocus>
            </div>
            <div class="form-group">
                <label for="last_name">Last Name :</label>
                <input type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name') }}" required autocomplete="last_name" autofocus>
            </div>
            <div class="form-group">
                <input type="file" class="form-control-file" name="avatar" >
                <small class="form-text text-muted">Please upload a valid image file. Size of image should not be more than 2MB.</small>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                <a href="{{route('client.index')}}" class="btn btn-sm btn-danger">Cancel</a>
            </div>

        </form>

    </div>
@endsection

resources/views/client/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">

        <h3>Edit client</h3>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('client.update',$client->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="email">Email :</label>
                <input type="email" value="{{$client->email}}" class="form-control @error('email') is-invalid @enderror" name="email" required autocomplete="email" autofocus>
            </div>
            <div class="form-group">
                <label for="first_name">First Name :</label>
                <input type="text" value="{{$client->first_name}}" class="form-control @error('first_name') is-invalid @enderror" name="first_name" required autocomplete="first_name" autofocus>
            </div>
            <div class="form-group">
                <label for="last_name">Last Name :</label>
                <input type="text" value="{{$client->last_name}}" class="form-control @error('last_name') is-invalid @enderror" name="last_name" required autocomplete="last_name" autofocus>
            </div>
            <div class="form-group">
                <input type="file" class="form-control-file" name="avatar" value="{{$client->avatar}}" >
                <small class="form-text text-muted">Please upload a valid image file. Size of image should not be more than 2MB.</small>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-sm btn-success">Save</button>
                <a href="{{route('client.index')}}" class="btn btn-sm btn-danger">Cancel</a>
            </div>
        </form>
    </div>
@endsection

resources/views/client/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="d-flex justify-content-between flex-wrap">
            <div class="p-2">
                <h3>Clients</h3>
            </div>
            <div class="p-2">
                <a class="btn btn-sm btn-success mb-4" href="{{ route('client.create') }}"><i class="far fa-plus-square"> New</i></a>
            </div>
        </div>

        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{$message}}</p>
            </div>
        @endif
        <div class="table-responsive">
            <table class="table table-hover table-sm">
                <thead>
                    <tr>
                        <th width="5%" scope="col">#</th>
                        <th width="20%" scope="col">First Name</th>
                        <th width="20%" scope="col">Last Name</th>
                        <th class="d-none d-sm-block" width="20%" scope="col">Email</th>
                        <th width="35%" scope="col" class="text-right">Action</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($clients as $client)
                        <tr>
                            <th scope="row">{{$client->id}}</th>
                            <td>{{$client->first_name}}</td>
                            <td>{{$client->last_name}}</td>
                            <td class="d-none d-sm-block">{{$client->email}}</td>
                            <td class="text-right">
                                <form action="{{ route('client.destroy', $client->id) }}" method="post">
                                    <a class="btn btn-sm btn-primary" href="{{route('client.show',$client->id)}}"><i class="far fa-eye"></i></a>
                                    <a class="btn btn-sm btn-warning" href="{{route('client.edit',$client->id)}}"><i class="far fa-edit"></i></a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-danger"><i class="far fa-trash-alt"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        <div>

        {!! $clients->links() !!}
    </div>
@endsection

resources/views/client/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-5 mx-auto">
                <h3>Client Details</h3>
                <hr>
                <div class="card text-center mb-4">
                    @if(empty($client->avatar))
                        <img class="card-img-top rounded-circle mx-auto d-block w-50"
                             src="{{url('img/avatar/default.jpg')}}" alt="Card image cap">
                    @else
                        <img class="card-img-top rounded-circle mx-auto d-block w-50"
                             src="{{url('storage/avatars')}}/{{$client->avatar}}" alt="Card image cap">
                    @endif
                    <div class="card-body">
                        <h5 class="card-title">{{$client->first_name}} {{$client->last_name}}</h5>
                        <p class="card-text">{{$client->email}}.</p>
                    </div>
                    <div class="card-body">
                        <a href="{{route('client.index')}}" class="btn btn-sm btn-danger">Back</a>
                    </div>
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseTransactions" aria-expanded="false" aria-controls="collapseTransactions">
                        View Transactions
                    </button>
                </div>
            </div>
            <div class="col-lg-7 collapse" id="collapseTransactions">
                <div >
                    <h3>Transactions</h3>
                    <hr>
                    @if ($transactions = App\Transaction::where('client_id', '=', $client->id)->get())

                        <table class="table table-hover table-bordered table-sm">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Amount</th>
                                <th scope="col">Date</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach ($transactions as $transaction)
                                <tr>
                                    <td>{{$transaction->id}}</td>
                                    <td>{{$transaction->amount}}</td>
                                    <td>{{$transaction->created_at}}</td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection